In [ ]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subpl

In [5]:
exercice1
tesla=yf.Ticker("TSLA")
tesla_data=tesla.history(period="1y")
tesla_data.reset_index(inplace=True)
tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2022-12-27 00:00:00-05:00,117.500000,119.669998,108.760002,109.099998,208643400,0.0,0.0
1,2022-12-28 00:00:00-05:00,110.349998,116.269997,108.239998,112.709999,221070500,0.0,0.0
2,2022-12-29 00:00:00-05:00,120.389999,123.570000,117.500000,121.820000,221923300,0.0,0.0
3,2022-12-30 00:00:00-05:00,119.949997,124.480003,119.750000,123.180000,157777300,0.0,0.0
4,2023-01-03 00:00:00-05:00,118.470001,118.800003,104.639999,108.099998,231402800,0.0,0.0

In [ ]:
exercice2

url = "https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue"
html_data  = requests.get(url).text
soup = BeautifulSoup(html_data,"html5lib")

soup.find_all("tbody")[1]
tesla_revenue = pd.DataFrame(columns=['Date', 'Revenue'])

for table in soup.find_all('table'):

    if ('Tesla Quarterly Revenue' in table.find('th').text):
        rows = table.find_all('tr')
        
        for row in rows:
            col = row.find_all('td')
            
            if col != []:
                date = col[0].text
                revenue = col[1].text.replace(',','').replace('$','')

                tesla_revenue = tesla_revenue.append({"Date":date, "Revenue":revenue}, ignore_index=True)
                
tesla_revenue["Revenue"] = tesla_revenue['Revenue'].str.replace(',|\$',"")

tesla_revenue.dropna(inplace=True)

tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]

tesla_revenue.tail()

In [ ]:
exercice3
make_graph(tesla_data,tesla_revenue,'Tesla')
GameStop = yf.Ticker("GME")
gme_data = GameStop.history(period = 'max')
gme_data.reset_index(inplace = True)
gme_data.head()

In [ ]:
exercice4
url = "https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue"
html_data = requests.get(url).text
soup = BeautifulSoup(html_data, "html.parser")
soup.find_all('title')
gme_revenue = pd.DataFrame(columns = ['Date', 'Revenue'])

for row in soup.find_all("tbody")[1].find_all("tr"):
    col = row.find_all("td")
    date = col[0].text
    revenue = col[1].text.replace("$", "").replace(",", "")
    
    gme_revenue = gme_revenue.append({"Date": date, "Revenue": revenue}, ignore_index = True)
tesla_revenue.dropna(inplace=True)
tesla_revenue = tesla_revenue[tesla_revenue['Revenue'] != ""]
gme_revenue.tail()

In [ ]:
exercice5
make_graph(tesla_data, tesla_revenue, 'Tesla'

In [ ]:
#exercice6
make_graph(gme_data, gme_revenue, 'GameStop')